# Generated by Django 4.1 on 2023-11-20 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0003_remove_operatingroom_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_profile_pic/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_department',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatientsystemApp.department', to_field='name_department'),
        ),
    ]
