# Generated by Django 4.1 on 2023-11-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0004_remove_bed_profile_pic_doctor_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='id_department',
            new_name='name_department',
        ),
    ]
