# Generated by Django 4.1 on 2023-11-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0005_rename_id_department_doctor_name_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatientsystemApp.department'),
        ),
    ]
