# Generated by Django 4.1 on 2023-11-20 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0006_alter_doctor_name_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inpatientsystemApp.department', to_field='name_department'),
        ),
    ]
