# Generated by Django 4.1 on 2023-11-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0009_doctor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='id_bed',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bed ID'),
        ),
    ]
