# Generated by Django 4.1 on 2023-11-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0010_alter_bed_id_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingroom',
            name='id_operating_room',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='OperatingRoom ID'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='id_operation',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Operation ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_patient',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Patient ID'),
        ),
        migrations.DeleteModel(
            name='OperationPerforming',
        ),
    ]
