# Generated by Django 4.2.7 on 2023-12-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0011_alter_operatingroom_id_operating_room_and_more'),
    ]

    operations = [
    ]
