# Generated by Django 4.2.7 on 2023-12-04 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inpatientsystemApp', '0012_auto_20231202_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='id_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inpatientsystemApp.doctor'),
        ),
    ]
